[agent]
  interval = "5s"
  flush_interval = "5s"

# =======================
#   INPUT MODBUS
# =======================
[[inputs.modbus]]
  name = "chiller_sim"
  controller = "tcp://10.100.100.203:1502"
  timeout = "5s"
  slave_id = 1

  [[inputs.modbus.register]]
    name = "temp_oat"
    register = "input"
    address = 3
    data_type = "float32"
    byte_order = "ABCD"

  [[inputs.modbus.register]]
    name = "ctrl_wt"
    register = "input"
    address = 5
    data_type = "float32"
    byte_order = "ABCD"

  [[inputs.modbus.register]]
    name = "setpoint_csp1"
    register = "holding"
    address = 899
    data_type = "float32"
    byte_order = "ABCD"

  [[inputs.modbus.register]]
    name = "setpoint_csp2"
    register = "holding"
    address = 901
    data_type = "float32"
    byte_order = "ABCD"

  [[inputs.modbus.register]]
    name = "alm_cooler_freeze_f"
    register = "discrete"
    address = 0
    data_type = "bool"


# =======================
#   OUTPUT → INFLUXDB v2
# =======================
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "$INFLUX_TOKEN"
  bucket = "modbus_bucket"
  org = "IkerOrg"
